In [1]:
import torch

# Making sure that torch is using the GPU

torch.cuda.current_device()

torch.cuda.device(0)

torch.cuda.get_device_name(0)

torch.cuda.is_available()


In [2]:
t1 = torch.tensor(4.)

In [3]:
print(type(t1))

<class 'torch.Tensor'>


In [4]:
t2 = torch.tensor([1,2.,3,4.])

In [5]:
print(t2)

tensor([1., 2., 3., 4.])


In [25]:
t3 = torch.tensor([[4,6],
                  [4,2],
                  [2.,4]])

t3


tensor([[4., 6.],
        [4., 2.],
        [2., 4.]])

In [7]:
t1.shape

torch.Size([])

In [8]:
t2.shape

torch.Size([4])

In [9]:
t3.shape

torch.Size([3, 2])

*It is not possible to create tensors with improper shape*

In [10]:
t5 = torch.tensor([[5.,6,7],
                  [4.,45],
                   [.8,.6,7]])

ValueError: expected sequence of length 3 at dim 1 (got 2)

# Tensor Operations and Gradients


In [11]:
# creating 3 Tensors
x = torch.tensor(4.)
b = torch.tensor(3., requires_grad = True)
w = torch.tensor(5., requires_grad = True)

In [12]:
#Arithmetic Operations
y = w*x + b
y

tensor(23., grad_fn=<AddBackward0>)

In [13]:
#compute derivates

y.backward()

In [14]:
# printing out derivatives

print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(4.)
dy/db:  tensor(1.)


# Tensor Functions

In [26]:
# creating a tensor with a fixed value for every element
t6 = torch.full((3,2) , 42. ,)

In [27]:
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [29]:
# concatenate two tensors with compatible shapes

t7  = torch.cat((t3,t6))

In [30]:
t7

tensor([[ 4.,  6.],
        [ 4.,  2.],
        [ 2.,  4.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [32]:
#compute sin of each element

t8 = torch.sin(t7)
t8

tensor([[-0.7568, -0.2794],
        [-0.7568,  0.9093],
        [ 0.9093, -0.7568],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [33]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.7568, -0.2794],
         [-0.7568,  0.9093]],

        [[ 0.9093, -0.7568],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Interoperatibility with NumPy

In [34]:
import numpy as np

In [35]:
x = np.array([[1,2],[3,4]])

In [36]:
x

array([[1, 2],
       [3, 4]])

In [37]:
y = torch.from_numpy(x)

In [38]:
y

tensor([[1, 2],
        [3, 4]])