# Torch Functions

An short introduction about PyTorch and about the chosen functions. 

- torch.arange()
- torch.hstack()
- torch.linspace()
- torch.transpose()
- torch.inverse()

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

# Function 1 - torch.arange()

Function returns a 1-D tensor of size [end-start / step], with values from the interval [start,end )  taken with common difference step beginning from start   



In [ ]:
# Working Example
a = torch.arange(6)

print(a)
print(a.shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])


Code takes 6 as an input returns a 1-D tensor of size [6] with ouputs ranging from 0 upto 6 ,exclusive of 6


In [ ]:
# Working Example
b = torch.arange(1,10,2)
print(b)
print(b.shape)

tensor([1, 3, 5, 7, 9])
torch.Size([5])


## Arguments

  * 1) start - 1 , lower bound
  * 2) end - 10 , upper bound
  * 3) step-size - 2, increment size

These specific set of inputs returns a 1-D tensor of size [5] with outputs ranging form 1 upto 10 , not including 10 


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.arange(1,10,-1)
print(c)

RuntimeError: ignored

the function's lower bound is 1 and the upper bound is again set to 10 but with an increment of -1 , the operation would break down .

Whenever you need to create a 1-D tensor for a specific range of values , torch.arange() could prove out to be handy and well quick too.


## Function 2 - torch.linspace()

**torch.linspace()** Return set of samples with in a given interval. 

**torch.linspace()** allows you to define how many values you get including the specified min and max value.




In [ ]:
# Example 1 - working
torch.linspace(0,10)

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4950,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

returns 100 evenly spaced out values within the interval [1,10]

In [ ]:
# Example 2 - working

torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

returns 5 evenly spaced values in the interval [0,10] including the max value(upper bound)

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(20,10,-1)

RuntimeError: ignored

The function would only break down if the step size is negative thats the only drawback i could find with the function

Moreover i wanted to put this function here just to showcase the difference between the **torch.arange()** and **torch.linspace()** , the most notable difference among the both are

* torch.arange() doesnt't include the upper bound whereas torch.linspace() does

* torch.linspace() would return evenly spaced numbers **over** a specified   interval whereas torch.arange() would return evenly spaced values **within** a given interval


## Function 3 - torch.transpose()

Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

The resulting out tensor shares it’s underlying storage with the input tensor, so changing the content of one would change the content of the other.

In [ ]:
# Example 1 - working
x = torch.randn(2,3)
x



tensor([[ 1.6536, -1.3462,  1.1331],
        [ 1.0278,  2.1670,  0.3751]])

In [ ]:
torch.transpose(x,0,1)

tensor([[ 1.6536,  1.0278],
        [-1.3462,  2.1670],
        [ 1.1331,  0.3751]])

Transpose is a very handy and frequently used tensor function , here in the above example it shows how you could transpose a 2x3 matrix into a 3x2 matrix or tensor to be very precise.

In [ ]:
# Example 2 - working

y = torch.randn(3,4)
y

tensor([[ 1.4113,  0.7446, -0.6192,  1.7490],
        [ 1.2260,  0.6563, -0.9258,  0.7746],
        [-0.2010, -0.5178,  1.0285,  0.6858]])

In [ ]:
torch.transpose(y,-2,1)

tensor([[ 1.4113,  1.2260, -0.2010],
        [ 0.7446,  0.6563, -0.5178],
        [-0.6192, -0.9258,  1.0285],
        [ 1.7490,  0.7746,  0.6858]])

the above code transforms a 3x4 matrix into a 4x3 matrix .

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.transpose(y,1,4)

IndexError: ignored

The above code would break down if the dimension input to the function is out of bounds.


torch.transpose is a useful function and one would come across it more often than any other function except pd.read_csv() haha .


## Function 4 - torch.hstack()

Stack tensors in sequence horizontally (column wise).

This is equivalent to concatenation along the first axis for 1-D tensors, and along the second axis for all other tensors.

In [ ]:
# Example 1 - working
a = torch.arange(1,6)
b = torch.linspace(1,5,5)

In [ ]:
c = torch.hstack((a,b))
print(c)

tensor([1., 2., 3., 4., 5., 1., 2., 3., 4., 5.])


The above code demonstrates how you could use both arange and linspace with a little manipulation to create the same tensors and then horizontally stack them. 

In [ ]:
# Example 2 - working
c = torch.tensor([[1],[2],[3]])
d = torch.tensor([[4],[5],[6]])
torch.hstack((c,d))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Stacks two 3x1 tensor to generate a 3x2 tensor .

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
e = torch.tensor([[1],[2],[3]])
f = torch.tensor([[4]])
torch.hstack((e,f))

RuntimeError: ignored

the function would break down with the size of tensor involved in the operation doesn't match.

# Function 5 - torch.inverse()

Takes the inverse of the square matrix input. input can be batches of 2D square tensors, in which case this function would return a tensor composed of individual inverses.

In [ ]:
# Example 1 - working
x = torch.rand(2, 2)
x

tensor([[0.4206, 0.3497],
        [0.4844, 0.9677]])

In [ ]:
torch.inverse(x)

tensor([[ 4.0731, -1.4720],
        [-2.0387,  1.7702]])

The code takes in a random values drawn tensor from the interval [2,2] and performs the inverse operation 

In [ ]:
# Example 2 - working
b = torch.rand(4).reshape(2,2)
b

tensor([[0.7479, 0.8705],
        [0.3385, 0.1068]])

In [ ]:
torch.inverse(b)

tensor([[-0.4974,  4.0531],
        [ 1.5761, -3.4824]])

takes in a 2x2 tensor of random values and perform the inverse operation.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
y = torch.rand(6).reshape(3,2)
y

tensor([[0.9503, 0.4184],
        [0.4110, 0.2054],
        [0.5771, 0.2513]])

In [ ]:

torch.inverse(y)

RuntimeError: ignored

torch.inverse() works only for square matrices and hence if the input matrix isn't a square matrix it would breakdown and throw a Runtime Error

The computation of the inverse of a matrix is ​​essential when dealing with linear algebraic computations.

## Conclusion

In this not so short notebook we discussed some of the essential tensor operations with the help of PyTorch.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...